version: '3'

services:
  migration_service:
    image: migrator:latest
    environment:
      CONFIG_FILE: /migrator_config
      DB_USER: root
      DB_PASSWORD: /run/secrets/db_root_password
      DB_HOST: database_store
      DB_NAME: datadb
    networks:
      - main
    secrets:
      - db_root_password
    configs:
      - migrator_config
    depends_on:
      database_store:
        condition: service_healthy


  auth_service:
    image: auth_server:latest
    container_name: auth_service
    environment:
      BASE_URL: "https://auth.${ROOT_DOMAIN}"
      CONFIG_FILE: /auth_config
      RBAC_MODEL_FILE: /rbac_model
      APP_SERVER_BASE_URL: "https://app.${ROOT_DOMAIN}"
      CACHE_ADDRESS: cache_store:6379
      CACHE_PASSWORD: /run/secrets/cache_password
      PUBSUB_ADDRESS: cache_store:6379
      PUBSUB_PASSWORD: /run/secrets/cache_password
      DB_USER: auth_user
      DB_PASSWORD: /run/secrets/db_auth_password
      DB_HOST: database_store
      DB_NAME: datadb
      DEFAULT_USER_EMAIL: "admin@${ROOT_DOMAIN}"
      DEFAULT_USER_PASSWORD: ${AUTH_DEFAULT_PASSWORD}
      DEFAULT_APP_CLIENT_ID: /run/secrets/oauth_client_id
      DEFAULT_APP_CLIENT_SECRET: /run/secrets/oauth_client_secret
      PASSWORD_SECRET: /run/secrets/auth_token_secret
      SESSION_SECRET: /run/secrets/auth_session_secret
      EMAIL_DOMAIN: ${ROOT_DOMAIN}
      EMAIL_USER: admin
      SMTP_DOMAIN: email_service
      ACCESS_TOKEN_PUBLIC_KEY: /run/secrets/access_token_public_key
      ACCESS_TOKEN_PRIVATE_KEY: /run/secrets/access_token_private_key
    secrets: 
      - db_auth_password
      - cache_password
      - oauth_client_id
      - oauth_client_secret
      - auth_token_secret
      - auth_session_secret
      - access_token_public_key
      - access_token_private_key
    configs:
      - auth_config
      - rbac_model
    networks:
      - main
    depends_on:
      migration_service:
        condition: service_completed_successfully
      cache_store:
        condition: service_healthy
  

  app_service:
    image: app_service:latest
    container_name: app_service
    environment:
      BASE_URL: "https://api.${ROOT_DOMAIN}"
      CONFIG_FILE: /app_config
      RBAC_MODEL_FILE: /rbac_model
      CACHE_ADDRESS: cache_store:6379
      CACHE_PASSWORD: /run/secrets/cache_password
      PUBSUB_ADDRESS: cache_store:6379
      PUBSUB_PASSWORD: /run/secrets/cache_password
      DB_USER: app_user
      DB_PASSWORD: /run/secrets/db_app_password
      DB_HOST: database_store
      DB_NAME: datadb
      INTERNAL_AUTH_SERVER_BASE_URL: http://auth_service
    secrets:
      - cache_password
      - db_app_password
    configs:
      - app_config
      - rbac_model
    networks:
      - main
    depends_on:
      migration_service:
        condition: service_completed_successfully
      cache_store:
        condition: service_healthy


  gateway_service:
    image: gateway_service:latest
    container_name: gateway_service
    environment:
      BASE_URL: "https://app.${ROOT_DOMAIN}"
      CONFIG_FILE: /gateway_config
      AUTH_SERVER_BASE_URL: "https://auth.${ROOT_DOMAIN}"
      INTERNAL_AUTH_SERVER_DOMAIN: auth_service
      INTERNAL_APP_SERVER_DOMAIN: app_service
      CACHE_ADDRESS: cache_store:6379
      CACHE_PASSWORD: /run/secrets/cache_password
      SESSION_SECRET: /run/secrets/app_session_secret
      OAUTH_CLIENT_ID: /run/secrets/oauth_client_id
      OAUTH_CLIENT_SECRET: /run/secrets/oauth_client_secret
    secrets:
      - cache_password
      - app_session_secret
      - oauth_client_id
      - oauth_client_secret
    configs:
      - gateway_config
    networks:
      - main
    depends_on:
      cache_store:
        condition: service_healthy


  email_service:
    container_name: email_service
    image: mailer:latest
    environment:
      EMAIL_DOMAIN: ${ROOT_DOMAIN}
      CONFIG_FILE: /mail_config
      DKIM_PRIVATE_KEY: /run/secrets/dkim_private_key
    secrets:
      - dkim_private_key
    configs:
      - mail_config
    networks:
      - main
  

  database_store:
    image: database:latest
    container_name: database_store
    networks:
      - main
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
      MYSQL_DATABASE: datadb
      DB_AUTH_USER: auth_user
      INITIAL_DB_AUTH_PASSWORD: ${DB_AUTH_PASSWORD}
      DB_APP_USER: app_user
      INITIAL_DB_APP_PASSWORD: ${DB_APP_PASSWORD}
    secrets:
      - db_root_password
    volumes:
      - database_data:/var/lib/mysql
  

  cache_store:
    image: cache:latest
    container_name: cache_store 
    environment:
      CACHE_PASSWORD: /run/secrets/cache_password
    secrets:
      - cache_password
    networks:
      - main
    volumes:
      - cache_data:/data
  
  proxy:
    image: proxy:latest
    container_name: reverse_proxy
    ports:
      - "443:443"
    networks:
      - main
    environment:
      ROOT_DOMAIN: ${ROOT_DOMAIN}
      INTERNAL_AUTH_SERVER_DOMAIN: auth_service
      INTERNAL_APP_SERVER_DOMAIN: app_service
      INTERNAL_GATEWAY_SERVER_DOMAIN: gateway_service
      SSL_PUBLIC_KEY: /run/secrets/ssl_public_key
      SSL_PRIVATE_KEY: /run/secrets/ssl_private_key
    secrets:
      - ssl_public_key
      - ssl_private_key
    depends_on:
      auth_service:
        condition: service_started
      app_service:
        condition: service_started
      gateway_service:
        condition: service_started

volumes:
  database_data:
  cache_data:

networks:
  main:
    name: main
    driver: bridge

secrets:
  db_root_password:
    environment: "DB_ROOT_PASSWORD"
  db_auth_password:
    environment: "DB_AUTH_PASSWORD"
  db_app_password:
    environment: "DB_APP_PASSWORD"
  cache_password:
    environment: "CACHE_PASSWORD"
  oauth_client_id:
    environment: "DEFAULT_OAUTH_CLIENT_ID"
  oauth_client_secret:
    environment: "DEFAULT_OAUTH_CLIENT_SECRET"
  auth_token_secret:
    environment: "AUTH_TOKEN_SECRET"
  auth_session_secret:
    environment: "AUTH_SESSION_SECRET"
  app_session_secret:
    environment: "APP_SESSION_SECRET"
  access_token_public_key:
    file: ../keys/token.pem
  access_token_private_key:
    file: ../keys/token-key.pem
  dkim_private_key:
    file: ../keys/dkim-key.pem
  ssl_public_key:
    file: ../keys/_wildcard.joshrasmussen.dev.pem
  ssl_private_key:
    file: ../keys/_wildcard.joshrasmussen.dev-key.pem

configs:
  auth_config:
    file: ../configs/auth.yaml
  app_config:
    file: ../configs/app.yaml
  gateway_config:
    file: ../configs/gateway.yaml
  mail_config:
    file: ../configs/mail.yaml
  migrator_config:
    file: ../configs/migrator.yaml
  rbac_model:
    file: ../configs/rbac_model.conf

