server:
  port: 3333
  idle_timeout: 60s
  read_timeout: 1s
  write_timeout: 2s

cache:
  address: app-redis-store:6379
  password: password

pubsub:
  address: pubsub:6379
  password: password

auth_server: http://auth-service:3334

database:
  path: "app-user:password@tcp(app-mysql)/app-db?parseTime=true&multiStatements=true"
  migrations:
    - "./migrations/app/*.sql"

