server:
  port: 80
  idle_timeout: 60s
  read_timeout: 1s
  write_timeout: 2s
  base_url: https://api.spedue.com

cache:
  address: redis_store:6379
  password: password

pubsub:
  address: redis_store:6379
  password: password

auth_server: http://auth_service

database:
  path: "app_user:app_password@tcp(mysql_store)/datadb?parseTime=true&multiStatements=true"
  migrations:
    - "./migrations/app/*.sql"

