# Required Environment Variables:
# - BASE_URL
# - CACHE_ADDRESS
# - CACHE_PASSWORD
# - PUBSUB_ADDRESS
# - PUBSUB_PASSWORD
# - DB_USER
# - DB_PASSWORD
# - DB_HOST
# - DB_NAME 
# - DEFAULT_USER_EMAIL
# - DEFAULT_USER_PASSWORD
# - DEFAULT_APP_CLIENT_ID
# - DEFAULT_APP_CLIENT_SECRET
# - APP_SERVER_BASE_URL
# - PASSWORD_SECRET
# - SESSION_SECRET
# - EMAIL_DOMAIN
# - EMAIL_USER
# - SMTP_DOMAIN

server:
  port: 80
  idle_timeout: 60s
  read_timeout: 1s
  write_timeout: 2s
  base_url: ${BASE_URL}

cache:
  address: ${CACHE_ADDRESS}
  password: ${CACHE_PASSWORD}

pubsub:
  address: ${PUBSUB_ADDRESS}
  password: ${PUBSUB_PASSWORD}

database:
  user: ${DB_USER}
  pass: ${DB_PASSWORD}
  host: ${DB_HOST}
  db_name: ${DB_NAME}

notifications:
  timeout: 1s

template:
  common: 
    - "./templates/components/*.html"
  paths:
    - "./templates/pages/*.html"

default_user:
  email: ${DEFAULT_USER_EMAIL}
  password: ${DEFAULT_USER_PASSWORD}

default_app:
  client_id: ${DEFAULT_APP_CLIENT_ID}
  client_secret: ${DEFAULT_APP_CLIENT_SECRET}
  name: "Default App"
  description: "Used for app server"
  redirect_uri: ${APP_SERVER_BASE_URL}/oauth/callback

password_config:
  iterations: 3
  memory: 32768
  parallelism: 4
  hash_length: 32
  salt_length: 16
  secret: ${PASSWORD_SECRET}

verify_ttl: 300s
password_forgot_ttl: 300s
invite_ttl: 86400s
auth_code_ttl: 60s

access_token:
  public_key_path: ./keys/public.pem
  private_key_path: ./keys/private.pem
  ttl: 3600s

session:
  ttl: 3600s 
  cookie_ttl: 86400s 
  key: ${SESSION_SECRET}

email:
  domain: ${EMAIL_DOMAIN}
  user: ${EMAIL_USER}
  smtp_domain: ${SMTP_DOMAIN}
  smtp_port: 25
