server:
  port: 80
  idle_timeout: 60s
  read_timeout: 1s
  write_timeout: 2s
  base_url: https://auth.spedue.com

cache:
  address: redis_store:6379
  password: password

pubsub:
  address: redis_store:6379
  password: password

database:
  path: "auth_user:auth_password@tcp(mysql_store)/datadb?parseTime=true&multiStatements=true"

notifications:
  timeout: 1s

template:
  common: 
    - "./templates/auth/components/*.html"
  paths:
    - "./templates/auth/pages/*.html"

default_user:
  email: "joshrasmussen34@gmail.com"
  password: "password"

default_app:
  client_id: "efae5523-7585-4eae-8f4d-97897e0626f4"
  client_secret: "965963cf-752d-4f0a-84ea-affba4e55d61"
  name: "Default App"
  description: "Used for app server"
  redirect_uri: "https://app.spedue.com/oauth/callback"

password_config:
  iterations: 3
  memory: 32768
  parallelism: 4
  hash_length: 32
  salt_length: 16

  # TODO: Environment Variable?
  secret: SECRET

verify_ttl: 300s
password_forgot_ttl: 300s
invite_ttl: 86400s
auth_code_ttl: 60s

access_token:
  public_key_path: ./keys/public.pem
  private_key_path: ./keys/private.pem
  ttl: 3600s

session:
  ttl: 3600s 
  cookie_ttl: 86400s 

  # TODO: Environment Variable?
  key: SESSIONSECRET

email:
  domain: joshrasmussen.dev
  user: admin
  smtp_domain: email_service
  smtp_port: 25
