default_user:
  username: "root"
  email: "joshrasmussen34@gmail.com"
  password: "password"

password_config:
  iterations: 3
  memory: 32768
  parallelism: 4
  hash_length: 32
  salt_length: 16

general:
  server:
    port: 3334
    idle_timeout: 60s
    read_timeout: 1s
    write_timeout: 2s
 
  database:
    path: "./auth.db"
    migrations:
      - "./migrations/auth/*.sql"
  
  template:
    common: 
      - "./templates/auth/components/*.html"
    paths:
      - "./templates/auth/pages/*.html"


