default_user:
  email: "joshrasmussen34@gmail.com"
  password: "password"

password_config:
  iterations: 3
  memory: 32768
  parallelism: 4
  hash_length: 32
  salt_length: 16

  # TODO: Environment Variable?
  secret: SECRET

verify_ttl: 300s
password_forgot_ttl: 300s
invite_ttl: 86400s

session:
  ttl: 3600s 
  cookie_ttl: 86400s 

  # TODO: Environment Variable?
  key: SESSIONSECRET

general:
  server:
    port: 3334
    idle_timeout: 60s
    read_timeout: 1s
    write_timeout: 2s

  redis:
    address: auth-redis:6379
    password: password
 
  database:
    path: "auth-user:password@tcp(auth-mysql)/auth-db?parseTime=true&multiStatements=true"
    migrations:
      - "./migrations/auth/*.sql"

  notifications:
    timeout: 1s
  
  template:
    common: 
      - "./templates/auth/components/*.html"
    paths:
      - "./templates/auth/pages/*.html"


