default_user:
  email: "joshrasmussen34@gmail.com"
  password: "password"

password_config:
  iterations: 3
  memory: 32768
  parallelism: 4
  hash_length: 32
  salt_length: 16

general:
  server:
    port: 3334
    idle_timeout: 60s
    read_timeout: 1s
    write_timeout: 2s

  session:
    address: auth-redis:6379
    password: password
    ttl: 3600s 
    cookie_ttl: 86400s 
 
  database:
    path: "auth-user:password@tcp(auth-mysql)/auth-db?parseTime=true&multiStatements=true"
    migrations:
      - "./migrations/auth/*.sql"
  
  template:
    common: 
      - "./templates/auth/components/*.html"
    paths:
      - "./templates/auth/pages/*.html"


