server:
  port: 3332
  idle_timeout: 60s
  read_timeout: 1s
  write_timeout: 2s

cache:
  address: app-redis-store:6379
  password: password

session:
  ttl: 3600s 
  cookie_ttl: 86400s 

  # TODO: Environment Variable?
  key: SESSIONSECRET

notifications:
  timeout: 1s

template:
  common: 
    - "./templates/app/components/*.html"
  paths:
    - "./templates/app/pages/*.html"


