server:
  port: 80
  idle_timeout: 60s
  read_timeout: 1s
  write_timeout: 2s

cache:
  address: app_redis_store:6379
  password: password

session:
  ttl: 3600s 
  cookie_ttl: 86400s 
  key: SESSIONSECRET

notifications:
  timeout: 1s

external_auth_server: https://auth.spedue.com
auth_server: http://auth_service
app_server: app_service
base_url: https://app.spedue.com

oauth:
  client_id: "efae5523-7585-4eae-8f4d-97897e0626f4"
  client_secret: "965963cf-752d-4f0a-84ea-affba4e55d61"
  authorize_uri: /oauth/authorize
  token_uri: /oauth/token

template:
  common: 
    - "./templates/app/components/*.html"
  paths:
    - "./templates/app/pages/*.html"


