# Required Environment Variables:
# - BASE_URL
# - CACHE_ADDRESS
# - CACHE_PASSWORD
# - SESSION_SECRET
# - OAUTH_CLIENT_ID
# - OAUTH_CLIENT_SECRET
# - AUTH_SERVER_BASE_URL
# - INTERNAL_AUTH_SERVER_BASE_URL

server:
  port: 80
  idle_timeout: 60s
  read_timeout: 1s
  write_timeout: 2s
  base_url: ${BASE_URL}

cache:
  address: ${CACHE_ADDRESS}
  password: ${CACHE_PASSWORD}

session:
  ttl: 3600s 
  cookie_ttl: 86400s 
  key: ${SESSION_SECRET}

notifications:
  timeout: 1s

oauth:
  client_id: ${OAUTH_CLIENT_ID}
  client_secret: ${OAUTH_CLIENT_SECRET} 
  redirect_authorize_uri: ${AUTH_SERVER_BASE_URL}/oauth/authorize
  token_uri: http://${INTERNAL_AUTH_SERVER_DOMAIN}/oauth/token

app_server: ${INTERNAL_APP_SERVER_DOMAIN}

template:
  common: 
    - "./templates/gateway/components/*.html"
  paths:
    - "./templates/gateway/pages/*.html"


