port: 25
protocol: tcp4

dkim:
  selector: dkim2
  domain: joshrasmussen.dev
  headers:
    - From
    - To
    - Subject
    - Message-ID
    - Date
  private_key_path: ./keys/dkim-private.pem

forwarder:
  common_ports: 
    - 25
    - 2525
    - 587

