# Required Environement Variables:
# - EMAIL_DOMAIN

port: 587
protocol: tcp4

read_timeout: 60s
write_timeout: 60s
data_timeout: 5m
max_message_size: 10240000
max_recipients: 100

auth_credentials: ${CREDENTIALS_FILE} 

tls:
  certificate_path: ${TLS_CERTIFICATE_PATH}
  key_path: ${TLS_KEY_PATH}

dkim:
  selector: dkim2
  domain: ${EMAIL_DOMAIN}
  headers:
    - From
    - To
    - Subject
    - Message-ID
    - Date
  private_key_path: ${DKIM_PRIVATE_KEY}

forwarder:
  common_ports: 
    - 25
    - 2525
    - 587

