port: 25
protocol: tcp4

read_timeout: 60s
write_timeout: 60s
data_timeout: 5m
max_message_size: 10240000
max_recipients: 100

dkim:
  selector: dkim2
  domain: joshrasmussen.dev
  headers:
    - From
    - To
    - Subject
    - Message-ID
    - Date
  private_key_path: ./keys/dkim-private.pem

forwarder:
  common_ports: 
    - 25
    - 2525
    - 587

